export interface Property {
  id: number
  title: string
  price: number
  annualPrice?: number
  location: string
  bedrooms: number
  bathrooms: number
  area: number
  type: "For Sale" | "For Rent"
  image: string
  images: string[]
  description: string
  features: string[]
  yearBuilt: number
  phoneNumber: string
}

export const properties: Property[] = [
  {
    id: 1,
    title: "Modern Luxury Villa with Pool",
    price: 1250000,
    location: "Palm Jumeirah, Dubai",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    type: "For Sale",
    image: "/luxury-villa-exterior.png",
    images: [
      "/luxury-villa-exterior.png",
      "/luxury-villa-interior-1.jpg",
      "/luxury-villa-interior-2.jpg",
      "/luxury-villa-pool.jpg",
      "/luxury-villa-kitchen.png",
    ],
    description:
      "This stunning modern villa offers luxurious living in one of Dubai's most prestigious locations. Featuring an open floor plan with high ceilings and floor-to-ceiling windows that flood the space with natural light.\n\nThe property includes a private swimming pool, landscaped garden, and a spacious terrace perfect for entertaining. The gourmet kitchen is equipped with high-end appliances and custom cabinetry.\n\nLocated in Palm Jumeirah, residents enjoy exclusive beach access, 24/7 security, and proximity to fine dining, shopping, and entertainment venues.",
    features: [
      "Private Swimming Pool",
      "Smart Home System",
      "Home Theater",
      "Private Garden",
      "Maid's Room",
      "Walk-in Closets",
      "Double Garage",
      "Marble Flooring",
      "24/7 Security",
      "Beach Access",
    ],
    yearBuilt: 2020,
    phoneNumber: "+962790680585",
  },
  {
    id: 2,
    title: "Downtown Apartment with City Views",
    price: 650000,
    location: "Downtown, Dubai",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    type: "For Sale",
    image: "/downtown-apartment-living.jpg",
    images: [
      "/downtown-apartment-living.jpg",
      "/downtown-apartment-kitchen.jpg",
      "/downtown-apartment-bedroom.jpg",
      "/downtown-apartment-bathroom.jpg",
      "/downtown-apartment-view.jpg",
    ],
    description:
      "Luxurious apartment in the heart of Downtown Dubai with breathtaking views of the Burj Khalifa and Dubai Fountain. This modern apartment features an open-concept living area, gourmet kitchen with premium appliances, and floor-to-ceiling windows that showcase the stunning city skyline.\n\nThe master bedroom includes a walk-in closet and an en-suite bathroom with a soaking tub and separate shower. The second bedroom is spacious and has its own bathroom.\n\nResidents enjoy access to world-class amenities including a swimming pool, fitness center, children's play area, and 24-hour concierge service. The building is within walking distance to Dubai Mall, restaurants, and entertainment venues.",
    features: [
      "Burj Khalifa View",
      "Floor-to-ceiling Windows",
      "Balcony",
      "Fitted Kitchen",
      "Walk-in Closet",
      "Swimming Pool",
      "Gym Access",
      "Concierge Service",
      "Covered Parking",
      "Central A/C",
    ],
    yearBuilt: 2018,
    phoneNumber: "+962790680585",
  },
  {
    id: 3,
    title: "Beachfront Condo",
    price: 4500,
    annualPrice: 54000,
    location: "JBR, Dubai", 
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    type: "For Rent",
    image: "/beachfront-condo-living.jpg",
    images: [
      "/beachfront-condo-living.jpg",
      "/beachfront-condo-kitchen.jpg",
      "/beachfront-condo-bedroom.jpg",
      "/beachfront-condo-bathroom.jpg",
      "/beachfront-condo-view.jpeg",
    ],
    description:
      "Stunning beachfront condo in Jumeirah Beach Residence with direct beach access and panoramic sea views. This fully furnished apartment offers a spacious living area that opens to a large balcony perfect for enjoying the beautiful Dubai sunsets.\n\nThe kitchen is fully equipped with high-end appliances and there is a separate dining area. The master bedroom features an en-suite bathroom and walk-in closet, while the two additional bedrooms are well-sized and share a bathroom.\n\nResidents enjoy access to premium amenities including multiple swimming pools, a state-of-the-art fitness center, children's play areas, and direct access to JBR Walk with its restaurants, cafes, and shops.",
    features: [
      "Sea View",
      "Fully Furnished",
      "Beach Access",
      "Balcony",
      "Swimming Pools",
      "Gym",
      "Children's Play Area",
      "24/7 Security",
      "Covered Parking",
      "Pet-Friendly",
    ],
    yearBuilt: 2016,
    phoneNumber: "+962790680585",
  },
  {
    id: 4,
    title: "Family Home in Suburban Area",
    price: 850000,
    location: "Arabian Ranches, Dubai",
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    type: "For Sale",
    image: "/suburban-home-exterior.jpg",
    images: [
      "/suburban-home-exterior.jpg",
      "/suburban-home-living.jpg",
      "/suburban-home-kitchen.jpg",
      "/suburban-home-bedroom.jpg",
      "/suburban-home-garden.jpg",
    ],
    description:
      "Beautiful family home in the prestigious Arabian Ranches community. This well-maintained property offers a perfect blend of comfort and luxury with its spacious layout and quality finishes.\n\nThe ground floor features a large living room, dining area, guest bedroom, and a modern kitchen with breakfast nook. Upstairs, you'll find the master bedroom with en-suite bathroom, two additional bedrooms, and a family bathroom.\n\nThe landscaped garden includes a covered patio area perfect for outdoor dining and entertaining. The community offers excellent amenities including swimming pools, parks, sports facilities, and international schools nearby.",
    features: [
      "Private Garden",
      "Covered Patio",
      "Study Room",
      "Maid's Room",
      "Storage Room",
      "Community Pool",
      "Tennis Courts",
      "Children's Play Area",
      "24/7 Security",
      "Close to Schools",
    ],
    yearBuilt: 2015,
    phoneNumber: "+962790680585",
  },
  {
    id: 5,
    title: "Penthouse with Panoramic Views",
    price: 7500,
    annualPrice: 90000,
    location: "Marina, Dubai",
    bedrooms: 4,
    bathrooms: 4,
    area: 2800,
    type: "For Rent",
    image: "/penthouse-living-room.jpg",
    images: [
      "/penthouse-living-room.jpg",
      "/penthouse-dining.jpg",
      "/penthouse-bedroom.jpg",
      "/penthouse-bathroom.jpg",
      "/penthouse-terrace.jpg",
    ],
    description:
      "Luxurious penthouse apartment in Dubai Marina offering breathtaking 360-degree views of the marina, sea, and city skyline. This exclusive residence spans the entire top floor and features premium finishes throughout.\n\nThe open-concept living area includes a gourmet kitchen with top-of-the-line appliances, a formal dining area, and a spacious lounge that opens to a wraparound terrace. The master suite includes a sitting area, walk-in closet, and a spa-like bathroom with a soaking tub and separate shower.\n\nAdditional features include smart home technology, private elevator access, and a dedicated staff quarter. The building offers premium amenities including an infinity pool, fitness center, and concierge services.",
    features: [
      "Panoramic Views",
      "Private Terrace",
      "Smart Home System",
      "Private Elevator",
      "Staff Quarters",
      "Infinity Pool",
      "Fitness Center",
      "Concierge Service",
      "Multiple Parking Spaces",
      "High Ceilings",
    ],
    yearBuilt: 2019,
    phoneNumber: "+962790680585",
  },
  {
    id: 6,
    title: "Townhouse with Private Garden",
    price: 1200,
    annualPrice: 14400,
    location: "Jumeirah Village Circle, Dubai",
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    type: "For Rent",
    image: "/townhouse-exterior.jpg",
    images: [
      "/townhouse-exterior.jpg",
      // "/townhouse-living.jpg",
      // "/townhouse-kitchen.jpg",
      // "/townhouse-bedroom.jpg",
      // "/townhouse-garden.jpg",
    ],
    description:
      "Modern townhouse in the family-friendly community of Jumeirah Village Circle. This well-designed property offers comfortable living spaces across three floors with high-quality finishes throughout.\n\nThe ground floor features an open-plan living and dining area, a modern kitchen, and a guest bathroom. The first floor houses two bedrooms with a shared bathroom, while the entire second floor is dedicated to the master suite with an en-suite bathroom and a private terrace.\n\nThe property includes a private garden, perfect for outdoor relaxation and entertaining. Residents enjoy access to community amenities including swimming pools, parks, and retail outlets. Conveniently located with easy access to major highways.",
    features: [
      "Private Garden",
      "Roof Terrace",
      "Built-in Wardrobes",
      "Modern Kitchen",
      "Guest Bathroom",
      "Community Pool",
      "Children's Play Area",
      "Covered Parking",
      "Security",
      "Near Schools",
    ],
    yearBuilt: 2017,
    phoneNumber: "+962790680585",
  },
  {
    id: 7,
    title: "Waterfront Villa with Private Beach",
    price: 3200000,
    location: "Palm Jumeirah, Dubai",
    bedrooms: 6,
    bathrooms: 7,
    area: 7000,
    type: "For Sale",
    image: "/waterfront-villa-exterior.jpg",
    images: [
      "/waterfront-villa-exterior.jpg",
      // "/waterfront-villa-living.jpg",
      // "/waterfront-villa-kitchen.jpg",
      // "/waterfront-villa-bedroom.jpg",
      // "/waterfront-villa-beach.jpg",
    ],
    description:
      "Exceptional waterfront villa on Palm Jumeirah with private beach access and unobstructed sea views. This magnificent property offers the ultimate in luxury living with expansive indoor and outdoor spaces designed for comfort and entertainment.\n\nThe grand entrance leads to a double-height living area with floor-to-ceiling windows showcasing the stunning sea views. The villa features a gourmet kitchen, formal dining room, family room, home theater, and a private office.\n\nThe master suite occupies an entire wing of the upper floor and includes a sitting area, walk-in dressing room, and a lavish bathroom with a freestanding tub. Five additional en-suite bedrooms provide ample space for family and guests.\n\nOutdoor amenities include an infinity pool, landscaped garden, private beach, and multiple terraces for dining and relaxation.",
    features: [
      "Private Beach Access",
      "Infinity Pool",
      "Home Theater",
      "Smart Home System",
      "Staff Quarters",
      "Elevator",
      "Wine Cellar",
      "Gym",
      "Sauna",
      "Multiple Terraces",
    ],
    yearBuilt: 2021,
    phoneNumber: "+962790680585",
  },
  {
    id: 8,
    title: "Modern Studio in Business Bay",
    price: 2800,
    annualPrice: 33600,
    location: "Business Bay, Dubai",
    bedrooms: 0,
    bathrooms: 1,
    area: 550,
    type: "For Rent",
    image: "/studio-apartment-living.jpg",
    images: [
      "/studio-apartment-living.jpg",
      // "/studio-apartment-kitchen.jpg",
      // "/studio-apartment-bathroom.jpg",
      // "/studio-apartment-view.jpg",
      // "/studio-apartment-building.jpg",
    ],
    description:
      "Contemporary studio apartment in the vibrant Business Bay district. This well-designed space maximizes functionality without compromising on style and comfort.\n\nThe open-plan layout features a sleeping area, living space, and a fully equipped kitchen with modern appliances. The bathroom includes a walk-in shower and premium fixtures.\n\nFloor-to-ceiling windows offer impressive views of the surrounding cityscape and fill the apartment with natural light. The unit comes fully furnished with high-quality furniture and accessories.\n\nThe building provides excellent amenities including a swimming pool, fitness center, and 24-hour security. Located within walking distance to Dubai Canal and a short drive to Downtown Dubai.",
    features: [
      "Fully Furnished",
      "City Views",
      "Built-in Wardrobes",
      "Modern Appliances",
      "Swimming Pool",
      "Gym",
      "Covered Parking",
      "24/7 Security",
      "Central A/C",
      "High-speed Internet",
    ],
    yearBuilt: 2019,
    phoneNumber: "+962790680585",
  },
  {
    id: 9,
    title: "Luxury Golf Course Villa",
    price: 1850000,
    location: "Emirates Hills, Dubai",
    bedrooms: 5,
    bathrooms: 6,
    area: 6000,
    type: "For Sale",
    image: "/golf-villa-exterior.jpg",
    images: [
      "/golf-villa-exterior.jpg",
      // "/golf-villa-living.jpg",
      // "/golf-villa-kitchen.jpg",
      // "/golf-villa-bedroom.jpg",
      // "/golf-villa-garden.jpg",
    ],
    description:
      "Prestigious villa overlooking the championship golf course in Emirates Hills. This exceptional property combines architectural elegance with modern luxury in one of Dubai's most exclusive communities.\n\nThe grand entrance leads to a spacious living area with high ceilings and panoramic views of the golf course. The ground floor includes a formal dining room, family room, gourmet kitchen with breakfast area, and a guest suite.\n\nThe upper level houses four en-suite bedrooms including the master suite with a private terrace, walk-in closet, and luxurious bathroom. The basement level features a home theater, gym, and staff quarters.\n\nThe outdoor space includes a swimming pool, landscaped garden, and covered terrace with outdoor kitchen and dining area. The property offers privacy and security in a prime location.",
    features: [
      "Golf Course View",
      "Private Swimming Pool",
      "Home Theater",
      "Gym",
      "Staff Quarters",
      "Smart Home System",
      "Outdoor Kitchen",
      "Multiple Terraces",
      "Double Garage",
      "24/7 Security",
    ],
    yearBuilt: 2016,
    phoneNumber: "+962790680585",
  },
]

export function getPropertyById(id: number): Property | undefined {
  return properties.find((property) => property.id === id)
}
