export interface Property {
  id: number;
  title: string;
  price: number | undefined;
  annualPrice?: number;
  location: string;
  googleMapsUrl?: string;
  bedrooms: number | undefined | string;
  toilets: number | undefined | string;
  area: number | undefined | string;
  type: 'For Sale' | 'For Rent';
  image: string;
  images: { url: string; title: string | undefined }[];
  description: string;
  features: string[];
  yearBuilt: number | undefined | string;
  phoneNumber: string;
}

export const properties: Property[] = [
  // {
  //   id: 1,
  //   title: 'Yamadadai Owner Change Property',
  //   price: 4500000,
  //   location: 'Yamadadai, Yachimata City, Chiba Prefecture',
  //   bedrooms: 4,
  //   toilets: 1,
  //   area: 108.89,
  //   type: 'For Sale',
  //   image: '/exterior-1.jpg',
  //   images: [
  //     { url: '/exterior-1.jpg', title: 'Exterior View' },
  //     { url: '/exterior-11.jpg', title: 'Additional Exterior View' },
  //     { url: '/entrance-1.jpg', title: 'Entrance' },
  //     { url: '/garden-1.jpg', title: 'Garden View' },
  //     { url: '/indoor-1.jpg', title: 'Indoor Space' },
  //     { url: '/kitchen-1.jpg', title: 'Kitchen' },
  //     { url: '/toilet-1.jpg', title: 'Bathroom' },
  //     { url: '/washroom-1.jpg', title: 'Washroom' },
  //     { url: '/indoor-11.jpg', title: 'Additional Indoor Space' },
  //     { url: '/indoor-111.jpg', title: 'Extra Indoor View' },
  //     { url: '/garden-11.jpg', title: 'Additional Garden View' },
  //   ],
  //   description:
  //     'This property is a 2-storey, wooden structure with 4 bedrooms, located in Yamadadai, Yachimata City, Chiba Prefecture. The land area is 286.99㎡ and the building area is 108.89㎡. Immediate delivery is available. Owner change property. For rent (all).',
  //   features: [
  //     '4 Bedrooms',
  //     '2-storey',
  //     'Wooden Structure',
  //     'Land Area 286.99㎡',
  //     'Building Area 108.89㎡',
  //     'Immediate Delivery',
  //     'Owner Change Property',
  //     'For Rent (all)',
  //     'Bike Parking',
  //     'Field Land Use',
  //     '60% Building Coverage Ratio',
  //     '200% Floor Area Ratio',
  //     'Ownership',
  //   ],
  //   yearBuilt: 1971,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 2,
  //   title: 'Kawaba 1-building apartment for rent',
  //   price: 21200000,
  //   location: 'Kawaba, Togane City, Chiba Prefecture',
  //   bedrooms: undefined,
  //   toilets: undefined,
  //   area: 238.48,
  //   type: 'For Sale',
  //   image: '/exterior-2.jpg',
  //   images: [
  //     { url: '/exterior-2.jpg', title: 'Exterior' },
  //     { url: '/exterior-22.jpg', title: 'Exterior' },
  //     { url: '/parking-2.jpg', title: 'Parking' },
  //     { url: '/floor-plan-2.jpg', title: 'Floor Plan' },
  //   ],
  //   description:
  //     '2-storey steel frame apartment for sale with 4 rooms, located in Kawaba, Togane City, Chiba Prefecture. Used area: 238.48㎡, land area: 226.23㎡. Parking available. Ownership. Built in November 1988 (35 years old). Immediate consultation for delivery.',
  //   features: [
  //     '2-storey',
  //     'Steel Frame',
  //     '4 Rooms',
  //     'Parking Available',
  //     'Bike Parking',
  //     'Ownership',
  //     'Residential Land',
  //     'Immediate Consultation for Delivery',
  //     'Current rent: 224,000 yen',
  //     'Management contract with external guarantee company',
  //     'Land area 226.23㎡',
  //     'Used area 238.48㎡',
  //     'Year Built: 1988',
  //     '6 units',
  //   ],
  //   yearBuilt: 1988,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 3,
  //   title: 'Used house in Honsuka, Sanmu city',
  //   price: 78000000,
  //   location: 'Honsuka, Sanmu City, Chiba Prefecture',
  //   bedrooms: 5,
  //   toilets: undefined,
  //   area: 205.62,
  //   type: 'For Sale',
  //   image: '/exterior-3.jpg',
  //   images: [
  //     { url: '/exterior-3.jpg', title: 'Exterior' },
  //     { url: '/entrance-3.jpg', title: 'Entrance' },
  //     { url: '/floor-plan-3.jpg', title: 'Floor plan' },
  //     { url: '/kitchen-3.jpg', title: 'Kitchen' },
  //     { url: '/toilet-3.jpg', title: 'Toilet' },
  //     { url: '/washroom-3.jpg', title: 'Washroom' },
  //     { url: '/indoor-3.jpg', title: 'Indoor' },
  //     { url: '/indoor-33.jpg', title: 'Indoor 2' },
  //     { url: '/indoor-333.jpg', title: 'Indoor 3' },
  //     { url: '/indoor-3333.jpg', title: 'Indoor 4' },
  //     { url: '/indoor-33333.jpg', title: 'Indoor 5' },
  //     { url: '/washroom-3.jpg', title: 'Washroom' },
  //     { url: '/living-3.jpg', title: 'Living' },
  //     { url: '/toilet-3.jpg', title: 'Toilet' },
  //     { url: '/parking-garage-3.jpg', title: 'Parking Garage' },
  //     { url: '/others-3.jpg', title: 'Other' },
  //     { url: '/other-local-3.jpg', title: 'Other Local' },
  //   ],
  //   description:
  //     'Japanese-style used house in Honsuka, Sanmu City, Chiba Prefecture. 2-storey, wooden structure, 5 bedrooms, building area 205.62㎡, land area 1577.5㎡. Built in June 2010 (14 years old). Parking for 2 or more cars, detached garage, close to the sea (4-minute walk to Motosuka beach). Spacious land, can be used as a vacation home. Immediate delivery available.',
  //   features: [
  //     '5 Bedrooms',
  //     '2-storey',
  //     'Wooden Structure',
  //     'Building Area 205.62㎡',
  //     'Land Area 1577.5㎡',
  //     'Built in 2010',
  //     'Parking for 2 or more cars',
  //     'Detached Garage',
  //     'Close to Sea (4-min walk to Motosuka beach)',
  //     'Vacation Home Potential',
  //     'Immediate Delivery',
  //     'Magnificent Gate',
  //     'Natural Materials',
  //     'Spacious Land',
  //     'Summer Resort',
  //     'Ownership',
  //     'Type 1 Residence Zoning',
  //     '60% Building Coverage Ratio',
  //     '200% Floor Area Ratio',
  //   ],
  //   yearBuilt: 2010,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 4,
  //   title: 'Oamishirasato City Kimimonori Used Detached House',
  //   price: 17800000,
  //   location: '2-chome, Kimimonoriminami, Oamishirasato City, Chiba Prefecture',
  //   bedrooms: 4,
  //   toilets: 2,
  //   area: 109.88,
  //   type: 'For Sale',
  //   image: '/exterior-4.jpg',
  //   images: [
  //     { url: '/exterior-4.jpg', title: 'Exterior' },
  //     { url: '/exterior-44.jpg', title: 'Exterior 2' },
  //     { url: '/floor-plan-4.jpg', title: 'Floor plan' },
  //     { url: '/entrance-4.jpg', title: 'Entrance' },
  //     { url: '/living-4.jpg', title: 'Living' },
  //     { url: '/kitchen-4.jpg', title: 'Kitchen' },
  //     { url: '/washroom-4.jpg', title: 'Washroom' },
  //     { url: '/washroom-44.jpg', title: 'Washroom 2' },
  //     { url: '/washroom-444.jpg', title: 'Washroom 3' },
  //     { url: '/indoor-4.jpg', title: 'Indoor' },
  //     { url: '/indoor-44.jpg', title: 'Indoor 2' },
  //     { url: '/indoor-444.jpg', title: 'Indoor 3' },
  //     { url: '/indoor-4444.jpg', title: 'Indoor 4' },
  //     { url: '/indoor-44444.jpg', title: 'Indoor 5' },
  //     { url: '/indoor-444444.jpg', title: 'Indoor 6' },
  //     { url: '/indoor-4444444.jpg', title: 'Indoor 7' },
  //     { url: '/garden-4.jpg', title: 'Garden' },
  //     { url: '/bus-4.jpg', title: 'Bus' },
  //     { url: '/toilet-4.jpg', title: 'Toilet' },
  //     { url: '/toilet-44.jpg', title: 'Toilet 2' },
  //   ],
  //   description:
  //     'Used detached house in Oamishirasato City, Kimimonoriminami, Chiba Prefecture. 2-storey, wooden structure, 4 bedrooms, building area 109.88㎡, land area 139.88㎡. Built in June 1997 (27 years old). Parking available, monitored intercom, reboiling function, city gas, residential land. Exterior (roof and exterior walls) renovated in May 2020. Located in a large development subdivision, close to parks and residential amenities.',
  //   features: [
  //     '4 Bedrooms',
  //     '2-storey',
  //     'Wooden Structure',
  //     'Building Area 109.88㎡',
  //     'Land Area 139.88㎡',
  //     'Built in 1997',
  //     'Parking Available',
  //     'Monitored Intercom',
  //     'Reboiling Function',
  //     'System Kitchen',
  //     'City Gas',
  //     'Low-rise Residential Area',
  //     'Residential Land',
  //     'Renovated in 2020 (roof, exterior walls)',
  //     'Large Development Subdivision',
  //     'Close to Parks',
  //     'Ownership',
  //     '1st Class Low Class Zoning',
  //     '50% Building Coverage Ratio',
  //     '100% Floor Area Ratio',
  //   ],
  //   yearBuilt: 1997,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 5,
  //   title: 'ComZ Village Tama',
  //   price: 37500000,
  //   annualPrice: undefined,
  //   location: 'Tama, Togane City, Chiba Prefecture',
  //   bedrooms: undefined,
  //   toilets: 1,
  //   area: 90.46,
  //   type: 'For Sale',
  //   image: '/exterior-5.jpg',
  //   images: [
  //     { url: '/exterior-5.jpg', title: 'Exterior' },
  //     { url: '/entrance-5.jpg', title: 'Entrance' },
  //     { url: '/entrance-55.jpg', title: 'Entrance 2' },
  //     { url: '/living-5.jpg', title: 'Living' },
  //     { url: '/living-55.jpg', title: 'Living 2' },
  //     { url: '/kitchen-5.jpg', title: 'Kitchen' },
  //     { url: '/washroom-5.jpg', title: 'Washroom' },
  //     { url: '/washroom-55.jpg', title: 'Washroom 2' },
  //     { url: '/toilet-5.jpg', title: 'Toilet' },
  //     { url: '/bus-5.jpg', title: 'Bus' },
  //     { url: '/floor-plan-5.jpg', title: 'Floor plan' },
  //     { url: '/indoor-5.jpg', title: 'Indoor' },
  //     { url: '/indoor-55.jpg', title: 'Indoor 2' },
  //     { url: '/indoor-555.jpg', title: 'Indoor 3' },
  //     { url: '/storage-5.jpg', title: 'Storage' },
  //     { url: '/storage-55.jpg', title: 'Storage 2' },
  //     { url: '/others-local-5.jpg', title: 'Other Local' },
  //     { url: '/BeisiaToganeStore24minuteswalk1870m-5.jpg', title: 'Beisia Togane Store (24 minutes walk, 1870m)' },
  //     {
  //       url: '/ToganeCityHigashiJuniorHighSchool16minuteswalk,1250m-5.jpg',
  //       title: 'Togane City Higashi Junior High School (16 minutes walk, 1250m)',
  //     },
  //   ],
  //   description:
  //     'ComZ Village Tama in Tama, Togane City, Chiba Prefecture. 1-storey, wooden structure, 3LDK, building area 90.46㎡, land area 200.7㎡. New construction, built in January 2025. Parking for 2 spaces, monitored intercom, reboiling function, solar power, eco-friendly, BELS/energy-saving standard compliant, public water supply, city gas, and residential land. Courtyard zone, walk-in closet, and more.',
  //   features: [
  //     '3LDK',
  //     '1-storey',
  //     'Wooden Structure',
  //     'Building Area 90.46㎡',
  //     'Land Area 200.7㎡',
  //     'New Construction (2025)',
  //     'Parking for 2 Spaces',
  //     'Monitored Intercom',
  //     'Reboiling Function',
  //     'Solar Power',
  //     'Eco-friendly',
  //     'Reheating Function',
  //     'Corner Lot',
  //     'BELS/Energy-saving Standard Compliant',
  //     'Public Water Supply',
  //     'Residential Land',
  //     'Courtyard Zone',
  //     'Walk-in Closet',
  //     'Type 1 Residence Zoning',
  //     '60% Building Coverage Ratio',
  //     '200% Floor Area Ratio',
  //   ],
  //   yearBuilt: 2025,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 6,
  //   title: 'Naruto 2M-1',
  //   price: 37800000,
  //   location: 'Naruto, Sanmu City, Chiba Prefecture',
  //   bedrooms: undefined,
  //   toilets: 2,
  //   area: 126.71,
  //   type: 'For Sale',
  //   image: '/exterior-6.jpg',
  //   images: [
  //     { url: '/exterior-6.jpg', title: 'Exterior' },
  //     { url: '/exterior-66.jpg', title: 'Exterior 2' },
  //     { url: '/entrance-6.jpg', title: 'Entrance' },
  //     { url: '/balcony-6.jpg', title: 'Balcony' },
  //     { url: '/indoor-6.jpg', title: 'Indoor' },
  //     { url: '/indoor-66.jpg', title: 'Indoor 2' },
  //     { url: '/storage-6.jpg', title: 'Storage' },
  //     { url: '/toilet-6.jpg', title: 'Toilet' },
  //     { url: '/toilet-second-floor-6.jpg', title: 'Toilet Second Floor' },
  //     { url: '/washroom-6.jpg', title: 'Washroom' },
  //     { url: '/bus-6.jpg', title: 'Bus' },
  //     { url: '/kitchen-stylish-island-6.jpg', title: 'Kitchen Stylish Island' },
  //     { url: '/living-it-comes-with-storage-for-toys-6.jpg', title: 'Living with Storage for Toys' },
  //     { url: '/living-kids-space-6.jpg', title: 'Living Kids Space' },
  //     { url: '/living-6.jpg', title: 'Living' },
  //     { url: '/floor-plan-6.jpg', title: 'Floor plan' },
  //   ],
  //   description:
  //     'Naruto 2M-1 in Naruto, Sanmu City, Chiba Prefecture. 2-storey, wooden structure, 3LDK, building area 126.71㎡, land area 238.19㎡. For sale. New construction, built in December 2024. Parking for 2 spaces, reboiling function, 2 or more toilets, low-rise residential area, highly airtight and insulated all-electric house, fully equipped, walk-in closet, and more.',
  //   features: [
  //     '3LDK',
  //     '2-storey',
  //     'Wooden Structure',
  //     'Building Area 126.71㎡',
  //     'Land Area 238.19㎡',
  //     'New Construction (2024)',
  //     'Parking for 2 Spaces',
  //     'Monitored Intercom',
  //     '2 or More Toilets',
  //     'Low-rise Residential Area',
  //     'Highly Airtight and Insulated',
  //     'All-electric House',
  //     'Fully Equipped',
  //     'Walk-in Closet',
  //     'Flat Topography',
  //     'Ownership',
  //     '60% Building Coverage Ratio',
  //     '200% Floor Area Ratio',
  //   ],
  //   yearBuilt: 2024,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 7,
  //   title: 'Maison Phoenix ABC+ Tenant',
  //   price: 80000000,
  //   annualPrice: undefined,
  //   location: 'Chiba Prefecture, Togane City, Kurume',
  //   bedrooms: undefined,
  //   toilets: undefined,
  //   area: 136.73,
  //   type: 'For Sale',
  //   image: '/exterior-2.jpg',
  //   images: [
  //     { url: '/exterior-7.jpg', title: 'Exterior' },
  //     { url: '/exterior-77.jpg', title: 'Exterior 2' },
  //     { url: '/exterior-777.jpg', title: 'Exterior 3' },
  //     { url: '/floor-plan-7.jpg', title: 'Floor plan' },
  //     { url: '/entrance-7.jpg', title: 'Entrance' },
  //     { url: '/entrance-77.jpg', title: 'Entrance 2' },
  //     { url: '/common-area-7.jpg', title: 'Common Area' },
  //     { url: '/balcony-7.jpg', title: 'Balcony' },
  //     { url: '/indoor-7.jpg', title: 'Indoor' },
  //     { url: '/indoor-77.jpg', title: 'Indoor 2' },
  //     { url: '/indoor-777.jpg', title: 'Indoor 3' },
  //     { url: '/storage-7.jpg', title: 'Storage' },
  //     { url: '/storage-77.jpg', title: 'Storage 2' },
  //     { url: '/bus-7.jpg', title: 'Bus' },
  //     { url: '/others-7.jpg', title: 'Others' },
  //     { url: '/KumeiStation-7.jpg', title: 'Kumei Station' },
  //   ],
  //   description:
  //     'Maison Phoenix ABC+ Tenant is a 2-storey wooden apartment building for sale in Kurume, Togane City, Chiba Prefecture. Used area: 136.73㎡, land area: 799.73㎡. 17 units (15 apartments + 3 office units). Currently partially rented. Built in February 1992 (33 years old). Bicycle parking available. Residential land. Ownership. Immediate consultation for delivery.',
  //   features: [
  //     '2-storey',
  //     'Wooden Structure',
  //     '17 Units (15 apartments + 3 office units)',
  //     'Partially Rented',
  //     'Bicycle Parking',
  //     'Residential Land',
  //     'Ownership',
  //     'Land Area 799.73㎡',
  //     'Building Area 136.73㎡',
  //     'Built in 1992',
  //     'Immediate Consultation for Delivery',
  //     'Flat Topography',
  //     'Non-lined Areas',
  //     'Studio Units',
  //   ],
  //   yearBuilt: 1992,
  //   phoneNumber: '+818033666526',
  // },
  {
    id: 8,
    title: 'Ōamishirasato City House',
    price: 3750000,
    location: '986-7 Yanagibashi, Ōamishirasato City, Chiba 299-3263',
    googleMapsUrl: 'https://maps.app.goo.gl/pTJ4HM8eLjTwBxUP7',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 'Please contact us for more information',
    type: 'For Sale',
    image: '/1 Ōamishirasato City House/Picture1.jpg',
    images: [
      { url: '/1 Ōamishirasato City House/Picture1.jpg', title: '' },
      { url: '/1 Ōamishirasato City House/Picture2.jpg', title: '' },
      { url: '/1 Ōamishirasato City House/Picture3.jpg', title: '' },
      { url: '/1 Ōamishirasato City House/Picture4.jpg', title: '' },
      { url: '/1 Ōamishirasato City House/Picture13.jpg', title: '' },
    ],
    description:
      'Affordable Investment Property in Ōamishirasato City – 16% Yield Potential! This is a unique opportunity to invest in a residential property located in the peaceful city of Ōamishirasato, Chiba Prefecture. Just 15 minutes from the nearest bus stop (Kisaki), this wooden-structured house is currently owner-occupied and could generate a steady income of ¥600,000 annually. With a projected yield of 16% and a low asking price of ¥3.75 million, this is a great entry point for investors looking to secure a high return with minimal risk. Ideal for long-term rental income or future owner occupancy.',
    features: [
      'Wooden Structure',
      'Owner-occupied',
      'Current Rent: ¥50,000/month',
      'Annual Income: ¥600,000/year',
      'Projected Yield: 16%',
      'Nearest Station: Kisaki (Bus Stop) – 15 minutes',
      'Layout: Please contact us for more information',
      'Building Area: Please contact us for more information',
      'Land Area: Please contact us for more information',
      'Parking: Please contact us for more information',
      'Investment Opportunity',
      'High Return Potential',
      'Long-term Rental Income',
      'Future Owner Occupancy',
      'Peaceful Location',
      'Minimal Risk Investment',
    ],
    yearBuilt: 'Please contact us for more information',
    phoneNumber: '+818033666526',
  },
  {
    id: 9,
    title: 'Yachimata 5LDK Family Home',
    price: undefined,
    location: '282-16 Negoya, Yachimata City, Chiba 289-1136',
    googleMapsUrl: 'https://maps.app.goo.gl/qPAxJAXTxhZfFX9o7',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 'Please contact us for more information',
    type: 'For Sale',
    image: '/2 Yachimata 5LDK Family Home/Picture1.jpg',
    images: [
      { url: '/2 Yachimata 5LDK Family Home/Picture1.jpg', title: '' },
      { url: '/2 Yachimata 5LDK Family Home/Picture6.jpg', title: '' },
      { url: '/2 Yachimata 5LDK Family Home/Picture7.jpg', title: '' },
      { url: '/2 Yachimata 5LDK Family Home/Picture8.jpg', title: '' },
      { url: '/2 Yachimata 5LDK Family Home/Picture9.jpg', title: '' },
      { url: '/2 Yachimata 5LDK Family Home/Picture10.jpg', title: '' },
      { url: '/2 Yachimata 5LDK Family Home/Picture11.jpg', title: '' },
      { url: '/2 Yachimata 5LDK Family Home/Picture12.jpg', title: '' },
    ],
    description:
      "Spacious 5LDK Family Home in Yachimata – Ideal for Living or Rental Investment! Discover a rare opportunity to own a fully renovated 5LDK house in the peaceful suburban area of Yachimata, Chiba Prefecture. Located just 10 minutes by car from Yachimata Station, this property offers a blend of comfort, space, and convenience. With one on-site parking space and a freshly renovated interior, this home is perfect for large families or as a rental investment. The property currently generates ¥60,000 in monthly rent and has additional potential for long-term value appreciation. Whether you're buying to live or invest, this is a golden opportunity to own a home in Japan with minimal upfront risk and clear income potential.",
    features: [
      '5LDK (5 rooms + Living, Dining, Kitchen)',
      'Current Rent: ¥60,000/month',
      'Nearest Station: Yachimata Station – 10 minutes by car',
      'Parking: 1 car space',
      'Renovated',
      'Layout: 5LDK (5 rooms + Living, Dining, Kitchen)',
      'Building Area: Please contact us for more information',
      'Land Area: Please contact us for more information',
      'Structure: Please contact us for more information',
      'Ownership: Please contact us for more information',
      'Annual Income: Please contact us for more information',
      'Projected Yield: Please contact us for more information',
      'Management System: Please contact us for more information',
      'Delivery: Please contact us for more information',
      'Additional Costs: 1-month brokerage fee, guarantor fee, fire insurance, 1-month interpreter fee',
      'Investment Opportunity',
      'Family Home',
      'Rental Potential',
      'Long-term Value Appreciation',
      'Minimal Upfront Risk',
      'Clear Income Potential',
    ],
    yearBuilt: 'Please contact us for more information',
    phoneNumber: '+818033666526',
  },
  {
    id: 10,
    title: 'Ashikaga City Matsuda Town 3LDK House',
    price: 2660000,
    location: '1643-3 Matsuda-cho, Ashikaga City, Tochigi 326-0101',
    googleMapsUrl: 'https://maps.app.goo.gl/FgsAoxry5t6M4BGF7',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 84.24,
    type: 'For Sale',
    image: '/3 Ashikaga City Matsuda Town 3LDK House/IMG_3749.jpg',
    images: [
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/IMG_3749.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/IMG_3822.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/IMG_3823.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/IMG_3742.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/IMG_3746.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/IMG_3747.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/松田町1.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/松田町2.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/松田町3.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/松田町間取り図.jpg', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/マップ小.JPG', title: '' },
      { url: '/3 Ashikaga City Matsuda Town 3LDK House/Picture17.jpg', title: '' },
    ],
    description:
      "Investment Property in Ashikaga City – Fully Tenanted 3LDK House with 18% ROI! An excellent opportunity to own a tenanted single-story Japanese home in Ashikaga City, Tochigi Prefecture. This 3LDK wooden house, built in 1970, sits on a generous 427.15㎡ lot and is currently rented for ¥40,000 per month, generating a stable annual income of ¥480,000. With an impressive projected yield of 18%, this property is ideal for real estate investors seeking solid returns with minimal risk. Located just 12 minutes by car from JR Yamamae Station, the house is equipped with essential utilities and includes a legally unregistered storage structure. The property lies within a regulated urban area but allows for reconstruction. Don't miss this high-yield, affordable investment opportunity in a peaceful, accessible suburban location.",
    features: [
      '3LDK (3 rooms + Living, Dining, Kitchen)',
      'Current Rent: ¥40,000/month',
      'Annual Income: ¥480,000/year',
      'Projected Yield: 18%',
      'Nearest Station: JR Ryomo Line – Yamamae Station (12 minutes by car)',
      'Year Built: April 1970 (Showa 45)',
      'Structure: Wooden, single-story house with tiled roof',
      'Floor Area: 84.24 ㎡',
      'Land Area: 427.15 ㎡ (Freehold)',
      'Parking: Available',
      'Ownership: Owner Change (tenanted)',
      'Management: With guarantee company',
      'Infrastructure: Well water, propane gas, TEPCO electricity, individual septic tank',
      'Other Features: Includes unregistered storage shed (19.83 ㎡)',
      'Road Access: 10m wide public road on south side, 3.67m frontage',
      'Zoning Category: Urbanization Control Area (Rebuilding allowed)',
      'Building-to-Land Ratio: Building Coverage Ratio: 60%, Floor Area Ratio: 200%',
      'Layout: 3LDK (3 rooms + Living, Dining, Kitchen)',
      'Building Area: 84.24 ㎡',
      'Land Area: 427.15 ㎡',
      'Bedrooms/Toilets: Please contact us for more information',
      'Tenant Rent: Please contact us for more information',
      'Occupancy Rate: Please contact us for more information',
      'Delivery: Please contact us for more information',
      'Investment Property',
      'High Yield Investment',
      'Fully Tenanted',
      'Stable Income',
      'Minimal Risk',
      'Reconstruction Allowed',
      'Affordable Investment',
    ],
    yearBuilt: 1970,
    phoneNumber: '+818033666526',
  },
  {
    id: 11,
    title: 'Yachimata City 4LDK House',
    price: 5800000,
    location: '624-19 Yoshikura, Yachimata City, Chiba 289-1133',
    googleMapsUrl: 'https://maps.app.goo.gl/Vw7761evMK3ZVGPp8',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 85.28,
    type: 'For Sale',
    image: '/4 Yachimata City 4LDK House/IMG_8462.jpg',
    images: [
      { url: '/4 Yachimata City 4LDK House/IMG_8462.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/IMG_8463.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/IMG_8464.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/IMG_8465.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/IMG_8466.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/IMG_8467.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/IMG_8468.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/IMG_8470.jpg', title: '' },
      { url: '/4 Yachimata City 4LDK House/吉倉間取り.jpeg', title: '' },
      { url: '/4 Yachimata City 4LDK House/マップ.jpg', title: '' },
    ],
    description:
      "Investment Opportunity in Yachimata City – Affordable 4LDK House with Rental Income! Here's your chance to own a two-story 4LDK wooden house in the quiet suburban area of Yachimata City, Chiba Prefecture. Built in 1992, this property offers a comfortable living space of 85.28㎡ on a 117㎡ plot and is currently rented out for ¥60,000 per month. With no deposit required and one month of free rent for tenants, this house offers potential for stable rental income with minimal upfront investment. It features two parking spaces and basic public utilities. Although there is a slight interior tilt of several centimeters, the property remains in use and is a cost-effective option for entry-level investors. Located just 15 minutes by car from JR Yachimata Station, this property also allows for residential use and is free from zoning restrictions. Additional purchase costs apply.",
    features: [
      '4LDK (4 rooms + Living, Dining, Kitchen)',
      'Current Rent: ¥60,000/month',
      'Nearest Station: JR Yachimata Station – 15 minutes by car',
      'Year Built: December 1992 (Heisei 4)',
      'Structure: Wooden, 2-story house with slate roof',
      'Floor Area: 85.28㎡',
      'Land Area: 117㎡ (Freehold; Land Category: Residential / Forest)',
      'Parking: Space for 2 vehicles',
      'Ownership: Freehold',
      'Infrastructure: Public water supply, drainage, electricity, propane gas',
      'Road Access: Existing private road (ownership share included)',
      'Zoning Category: Within city planning area; No specified zoning use',
      'Building-to-Land Ratio: Building Coverage Ratio: 60%, Floor Area Ratio: 200%',
      'Interior Condition: Slight tilt (a few centimeters)',
      'Building Type: Pre-owned detached house',
      'Additional Costs: Contract fees: ¥180,000 + fire insurance, guarantor fee (1 month), interpreter support (1 month), brokerage fee (1 month)',
      'Remarks: No deposit, 1-month free rent for tenants',
      'Layout: 4LDK (4 rooms + Living, Dining, Kitchen)',
      'Building Area: 85.28㎡',
      'Land Area: 117㎡',
      'Bedrooms/Toilets: Please contact us for more information',
      'Annual Income: Please contact us for more information',
      'Tenant Rent: Please contact us for more information',
      'Occupancy Rate: Please contact us for more information',
      'Projected Yield: Please contact us for more information',
      'Management: Please contact us for more information',
      'Delivery: Please contact us for more information',
      'Investment Opportunity',
      'Affordable Investment',
      'Rental Income',
      'Stable Income',
      'Minimal Upfront Investment',
      'Entry-level Investment',
      'Cost-effective Option',
      'Residential Use Allowed',
      'No Zoning Restrictions',
    ],
    yearBuilt: 1992,
    phoneNumber: '+818033666526',
  },
  {
    id: 12,
    title: 'Ōki, Sanmu City 5LDK House',
    price: 5800000,
    location: '826-30 Ōki, Sanmu City, Chiba 289-1211',
    googleMapsUrl: 'https://maps.app.goo.gl/vNVS1Fjozu3L34SWA',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 102.15,
    type: 'For Sale',
    image: '/5 Ōki, Sanmu City 5LDK House/20250327_111528-1_1743062431721.jpg',
    images: [
      { url: '/5 Ōki, Sanmu City 5LDK House/20250327_111528-1_1743062431721.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/20250327_111650-1_1743062431720.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/20250327_111726-1_1743062431771.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/20250327_111756-1_1743062582607.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/20250327_111507-1_1743062431772.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/IMG_8268.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/IMG_8265.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/IMG_8266.jpg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/526886C6-802E-45FD-BF42-171F4591519C.JPG', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/大木間取り図1 (2).jpeg', title: '' },
      { url: '/5 Ōki, Sanmu City 5LDK House/マップ.JPG', title: '' },
    ],
    description:
      "💼 Investment Property in Sanmu City – Spacious 5LDK House with 15% ROI! A great opportunity to invest in a spacious detached house in a peaceful residential area of Sanmu City, Chiba Prefecture. This 5LDK wooden house, built in 1988, offers 102.15㎡ of living space and sits on a freehold lot of 123.11㎡. The property is currently tenanted, generating a monthly rent of ¥65,000 and a stable annual income of ¥780,000 – providing an attractive projected yield of 15%. Located just 5 minutes by car from JR Yachimata Station, the house is situated on an east-facing corner lot and has undergone partial renovations. Infrastructure includes public water, electricity, propane gas, and a private septic tank. Don't miss this solid investment opportunity with strong returns and long-term potential.",
    features: [
      '5LDK (5 rooms + Living, Dining, Kitchen)',
      'Current Rent: ¥65,000/month',
      'Annual Income: ¥780,000/year',
      'Projected Yield: 15%',
      'Nearest Station: JR Yachimata Station – 5 minutes by car',
      'Year Built: April 1988 (Showa 63)',
      'Structure: Wooden, 2-story house with cement tile roof',
      'Floor Area: 102.15 ㎡',
      'Land Area: 123.11 ㎡ (Freehold)',
      'Parking: Available',
      'Ownership: Owner Change (tenanted)',
      'Infrastructure: Public water, electricity, propane gas, individual septic tank',
      'Road Access: Private road access (corner lot, east-facing)',
      'Zoning Category: Non-delineated urban area / No zoning restrictions',
      'Building-to-Land Ratio: Building Coverage Ratio: 60%, Floor Area Ratio: 200%',
      'Building Type: Used detached house',
      'Interior Condition: Partially renovated',
      'Remarks: Corner lot / Renovated',
      'Layout: 5LDK (5 rooms + Living, Dining, Kitchen)',
      'Building Area: 102.15 ㎡',
      'Land Area: 123.11 ㎡',
      'Bedrooms/Toilets: Please contact us for more information',
      'Tenant Rent: Please contact us for more information',
      'Occupancy Rate: Please contact us for more information',
      'Management: Please contact us for more information',
      'Delivery: Please contact us for more information',
      'Investment Property',
      'Spacious House',
      'Solid Investment',
      'Strong Returns',
      'Long-term Potential',
      'Corner Lot',
      'Partially Renovated',
      'Peaceful Location',
      'Stable Income',
    ],
    yearBuilt: 1988,
    phoneNumber: '+818033666526',
  },
  {
    id: 13,
    title: 'Kawaba – Multi-Unit Apartment Building',
    price: 21200000,
    location: '708-5 Kawaba, Togane City, Chiba 283-0064',
    googleMapsUrl: 'https://maps.app.goo.gl/WM6X5pporzDjxVP46',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 238.48,
    type: 'For Sale',
    image: '/6 Kawaba – Multi-Unit Apartment Building/Picture1.jpg',
    images: [
      { url: '/6 Kawaba – Multi-Unit Apartment Building/Picture1.jpg', title: '' },
      { url: '/6 Kawaba – Multi-Unit Apartment Building/Picture2.jpg', title: '' },
      { url: '/6 Kawaba – Multi-Unit Apartment Building/Picture3.jpg', title: '' },
      { url: '/6 Kawaba – Multi-Unit Apartment Building/Picture4.jpg', title: '' },
      { url: '/6 Kawaba – Multi-Unit Apartment Building/Picture5.jpg', title: '' },
    ],
    description:
      "🏢 High-Yield Multi-Unit Apartment Building in Togane City – Prime Corner Lot with Stable Income! This excellent investment opportunity features a multi-unit apartment building combined with a commercial food store located in Togane City, Chiba Prefecture. Built in 1988, the steel and wood-structured two-story building includes four residential units and a ground-floor commercial tenant space preparing to open soon. The property spans approximately 238.48㎡ on a corner lot with road access from two sides, offering parking for up to eight vehicles including bicycle spaces. Currently, six of seven units are rented, generating a steady monthly income of ¥224,000 with a strong occupancy rate of 86%. The full occupancy rent projection stands at ¥266,000 per month, resulting in an attractive expected yield of 15%. Situated just 5 minutes by car from JR Togane Station, this property is ideal for investors seeking high returns with diversified income streams. Additional benefits include external guarantee company coverage and partial recent renovations. Don't miss the chance to own this high-potential income-generating asset in a convenient location!",
    features: [
      'Multi-Unit Apartment Building',
      'Current Rent: ¥224,000/month (6 out of 7 units rented)',
      'Annual Income: ¥2,688,000/year (with guarantee company)',
      'Full Occupancy Rent: ¥266,000/month, ¥3,192,000/year (projected)',
      'Occupancy Rate: 86% (6 units occupied of 7 total)',
      'Expected Yield: 14% (current) / 15% (full occupancy)',
      'Nearest Station: JR Togane Station – 5 minutes by car',
      'Year Built: November 1988 (Showa 63), approximately 35 years old',
      'Structure: Steel frame and wooden structure, slate roof, 2-story (1F commercial + 2F residential)',
      'Layout: Total 4 rooms + 1F tenant commercial food store',
      'Building Area: 238.48 ㎡ (approx. 72.14 tsubo)',
      'Land Area: 226.23 ㎡ (approx. 68.43 tsubo, registered)',
      'Road Access: Corner lot with 4.2m road on west side, 8.1m road on north side',
      'Parking: Available for 8 cars including bicycle parking',
      'Ownership: Freehold (land)',
      'Zoning: Non-delineated area / No specific zoning',
      'Building Coverage / Floor Area Ratio: 60% / 200%',
      'Utilities: Propane gas, public water supply, individual septic tanks',
      'Management: External guarantee company contract included',
      'Delivery: Immediate delivery negotiable',
      'Remarks: Ground floor commercial food store preparing to open in June; partial renovations; corner lot; ideal for high-yield investment',
      'Bedrooms/Toilets: Please contact us for more information',
      'High-Yield Investment',
      'Multi-Unit Building',
      'Commercial + Residential',
      'Corner Lot',
      'Stable Income',
      'Diversified Income Streams',
      'High Returns',
      'Convenient Location',
      'Partial Renovations',
      'Income-Generating Asset',
    ],
    yearBuilt: 1988,
    phoneNumber: '+818033666526',
  },
  {
    id: 14,
    title: 'Narita Hotel',
    price: 39600000,
    location: '102-1 Yamamuro, Matsuo-cho, Sanmu City, Chiba 289-1501',
    googleMapsUrl: 'https://maps.app.goo.gl/35kVc1QFnnihWtX27',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 'Please contact us for more information',
    type: 'For Sale',
    image: '/7 Narita hotel/IMG_8060.jpg',
    images: [
      { url: '/7 Narita hotel/IMG_8060.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8044.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8045.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8046.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8047.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8048.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8049.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8050.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8051.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8052.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8053.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8054.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8055.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8056.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8057.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8058.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8059.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8287.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8411.jpg', title: '' },
      { url: '/7 Narita hotel/IMG_8413.jpg', title: '' },
      { url: '/7 Narita hotel/マップ小.jpg', title: '' },
      { url: '/7 Narita hotel/Picture39.jpg', title: '' },
      { url: '/7 Narita hotel/Picture38.jpg', title: '' },
    ],
    description:
      '💼 Prime Income-Generating Property in Sanmu City – High Monthly Rent with 15% Expected Yield! This outstanding investment opportunity is located in Sanmu City, Chiba Prefecture, just 15 minutes by car from Narita Airport. Offering a substantial monthly rental income of ¥495,000 and a projected annual yield of 15%, this property promises solid returns for investors seeking steady cash flow in a strategic location near a major transportation hub. The ownership is transferred with the property, which is scheduled to open by the end of August. Its attractive price point of ¥39,600,000 makes it an ideal choice for buyers looking to capitalize on a profitable rental asset in a growing area.',
    features: [
      'Hotel Property',
      'Current Rent: ¥495,000/month',
      'Annual Income: ¥5,940,000/year',
      'Expected Yield: 15%',
      'Nearest Station: Narita Airport – 15 minutes by car',
      'Ownership: Owner change',
      'Delivery: Scheduled to open by end of August',
      'Year Built: Please contact us for more information',
      'Structure: Please contact us for more information',
      'Layout: Please contact us for more information',
      'Floor Area: Please contact us for more information',
      'Land Area: Please contact us for more information',
      'Bedrooms/Toilets: Please contact us for more information',
      'Parking: Please contact us for more information',
      'Tenant Rent: Please contact us for more information',
      'Occupancy Rate: Please contact us for more information',
      'Management: Please contact us for more information',
      'Prime Investment Property',
      'High Monthly Rent',
      'Strategic Location',
      'Major Transportation Hub',
      'Steady Cash Flow',
      'Profitable Rental Asset',
      'Growing Area',
      'Income-Generating Property',
      'High Returns',
      'Solid Investment',
    ],
    yearBuilt: 'Please contact us for more information',
    phoneNumber: '+818033666526',
  },
  {
    id: 15,
    title: 'Yachimata City Yamada-dai 4LDK',
    price: 4500000,
    location: '674-8 Yamada-dai, Yachimata City, Chiba 289-1126',
    googleMapsUrl: 'https://maps.app.goo.gl/TzTj225Z3qpoiKUe6',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 76.17,
    type: 'For Sale',
    image: '/8 Yachimata City Yamada-dai 4LDK/20241101_110350-1_1730428406585.jpg',
    images: [
      { url: '/8 Yachimata City Yamada-dai 4LDK/20241101_110350-1_1730428406585.jpg', title: '' },
      { url: '/8 Yachimata City Yamada-dai 4LDK/20241101_110422-1_1730428406519.jpg', title: '' },
      { url: '/8 Yachimata City Yamada-dai 4LDK/20241101_110654-1_1730428406563.jpg', title: '' },
      { url: '/8 Yachimata City Yamada-dai 4LDK/20241101_110702-1_1730428406530.jpg', title: '' },
      { url: '/8 Yachimata City Yamada-dai 4LDK/20241101_110903-1_1730428650050.jpg', title: '' },
      { url: '/8 Yachimata City Yamada-dai 4LDK/20241101_111836-1_1730428650042.jpg', title: '' },
      { url: '/8 Yachimata City Yamada-dai 4LDK/マップ.JPG', title: '' },
    ],
    description:
      '💼 High-Yield Investment Property in Yachimata City – Fully Tenanted 4LDK House with 17.33% ROI! Discover a lucrative investment opportunity in Yachimata City, Chiba Prefecture. This well-maintained 4LDK wooden house with a galvanized metal roof offers a comfortable living space of 76.17㎡ and sits on a generous 286.99㎡ freehold land plot. Built in 1971 and renovated in 1979, the property features extensive repairs, remodeling, and professional cleaning, ensuring excellent condition for immediate tenancy. Currently leased at ¥65,000 per month, it generates a stable annual income of ¥780,000 with an impressive projected yield of 17.33%. Situated just 15 minutes by car from JR Togane Station, the house lies in an urbanization control area allowing for rebuilding, and includes essential utilities such as well water, propane gas, TEPCO electricity, and an individual septic tank. This property is an ideal choice for investors looking for a dependable, high-return asset in a quiet and accessible residential area.',
    features: [
      '4LDK (4 rooms + Living, Dining, Kitchen)',
      'Current Rent: ¥65,000/month',
      'Annual Income: ¥780,000/year',
      'Projected Yield: 17.33%',
      'Nearest Station: JR Togane Station – 15 minutes by car',
      'Year Built: December 1971 (Showa 46), Renovated April 1979 (Showa 54)',
      'Structure: Wooden structure with galvanized metal roof, 2 stories',
      'Floor Area: 76.17㎡',
      'Land Area: 286.99㎡ (Freehold)',
      'Parking: Space for 2 cars',
      'Ownership: Owner change (tenanted)',
      'Management: Includes guarantee company',
      'Delivery: Immediate',
      'Infrastructure: Well water, propane gas, TEPCO electricity, individual septic tank',
      'Zoning: Urbanization Control Area (Rebuilding permitted), Non-designated use area, Non-delimited zone',
      'Building-to-Land Ratio: Building Coverage Ratio: 60%, Floor Area Ratio: 200%',
      'Road Access: Southeast side: 5m road, Southwest side: 4m road',
      'Property Type: Used detached house',
      'Repair Status: Major renovations done, remodeled, house cleaning done',
      'Remarks: High yield property, owner-occupied with tenancy',
      'Layout: 4LDK (4 rooms + Living, Dining, Kitchen)',
      'Building Area: 76.17㎡',
      'Land Area: 286.99㎡',
      'Bedrooms/Toilets: Please contact us for more information',
      'Tenant Rent: Please contact us for more information',
      'Occupancy Rate: Please contact us for more information',
      'High-Yield Investment',
      'Fully Tenanted',
      'Well-Maintained',
      'Extensive Repairs',
      'Professional Cleaning',
      'Dependable Asset',
      'High-Return Investment',
      'Quiet Location',
      'Accessible Area',
      'Rebuilding Permitted',
    ],
    yearBuilt: 1971,
    phoneNumber: '+818033666526',
  },
  {
    id: 16,
    title: 'HARUMI FLAG SUN VILLAGE C-1610',
    price: 268000000,
    location: '5-5-3 Harumi, Chuo-ku, Tokyo 1610',
    googleMapsUrl: 'https://maps.app.goo.gl/EYxG2bkBEG2Ye5g69',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 106.57,
    type: 'For Sale',
    image: '/9 HARUMI FLAG SUN VILLAGE C-1610/Picture1.jpg',
    images: [
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/Picture1.jpg', title: '' },
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/写真1.jpg', title: '' },
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/写真2.jpg', title: '' },
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/写真3.jpg', title: '' },
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/写真4.jpg', title: '' },
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/写真5.jpg', title: '' },
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/写真6.jpg', title: '' },
      { url: '/9 HARUMI FLAG SUN VILLAGE C-1610/写真7.jpg', title: '' },
    ],
    description:
      "🌆 Luxury River View Penthouse at HARUMI FLAG SUN VILLAGE C-1610 – Modern 4LDK with Premium Amenities! Experience upscale urban living in this pristine, never-occupied penthouse located on the top floor of the prestigious HARUMI FLAG development in Tokyo's central Chuo Ward. Boasting a spacious 106.57㎡ layout with 4 bedrooms, walk-in closets (WIC), shoe-in closets (SIC), and additional storage (S), this residence offers an exceptional blend of comfort, style, and functionality. Enjoy breathtaking river views from the highest floor, complemented by state-of-the-art Panasonic Enefarm energy systems and air conditioning in every room. Pet owners will appreciate the pet-friendly policy allowing up to two dogs or cats. The building is managed professionally by Mitsubishi Estate Community Co., ensuring a secure and well-maintained environment. With immediate availability and a competitive price of ¥268,000,000 (tax included), this property is ideal for discerning buyers seeking a premium Tokyo residence or investment asset.",
    features: [
      '4LDK + Walk-In Closet (WIC) + Shoe-In Closet (SIC) + Storage (S)',
      'Year Built: November 2023 (Reiwa 5)',
      'Structure: Reinforced concrete with some steel, 16 floors above ground, 1 basement floor',
      'Floor Area: 106.57㎡',
      'Land Area: 37,441.27㎡ (registered, entire site)',
      'Parking: No car parking available; bicycle parking available; no motorcycle parking',
      'Ownership: Freehold',
      'Management: Fully outsourced (daytime) by Mitsubishi Estate Community Co., Ltd.',
      'Delivery: Immediate (vacant)',
      'Additional Fees: Management fee: ¥33,040/month; Repair reserve fund: ¥17,800/month; HARUMI FLAG CLUB membership: ¥500/month; Internet fees: ¥2,750/month; Property tax: TBD',
      'Remarks: Top floor river view, never occupied, pet-friendly (up to 2 dogs/cats), all rooms air-conditioned, Panasonic Enefarm system installed',
      'Layout: 4LDK + Walk-In Closet (WIC) + Shoe-In Closet (SIC) + Storage (S)',
      'Building Area: 106.57㎡',
      'Land Area: 37,441.27㎡',
      'Bedrooms/Toilets: Please contact us for more information',
      'Nearest Station: Please contact us for more information',
      'Current Rent: Please contact us for more information',
      'Annual Income: Please contact us for more information',
      'Tenant Rent: Please contact us for more information',
      'Occupancy Rate: Please contact us for more information',
      'Projected Yield: Please contact us for more information',
      'Luxury Penthouse',
      'River View',
      'Top Floor',
      'Never Occupied',
      'Premium Amenities',
      'Pet-Friendly',
      'Panasonic Enefarm System',
      'Air-Conditioned',
      'Walk-in Closets',
      'Premium Tokyo Residence',
      'Investment Asset',
      'Upscale Urban Living',
      'Prestigious Development',
      'Professional Management',
    ],
    yearBuilt: 2023,
    phoneNumber: '+818033666526',
  },
  {
    id: 17,
    title: 'Kihara Prefabricated Land + Office',
    price: 1660000,
    location: '738-59 Kihara, Sanmu City, Chiba 289-1214',
    googleMapsUrl: 'https://maps.app.goo.gl/VXXnrZiyM242rZTFA',
    bedrooms: 'Please contact us for more information',
    toilets: 'Please contact us for more information',
    area: 'Please contact us for more information',
    type: 'For Sale',
    image: '/10 Kihara Prefabricated Land + Office/Picture1.png',
    images: [
      { url: '/10 Kihara Prefabricated Land + Office/Picture1.png', title: '' },
      { url: '/10 Kihara Prefabricated Land + Office/Picture2.png', title: '' },
      { url: '/10 Kihara Prefabricated Land + Office/Picture3.png', title: '' },
      { url: '/10 Kihara Prefabricated Land + Office/Picture4.png', title: '' },
    ],
    description:
      "💼 Investment Property Profile – Kihara Prefabricated Office with High-Yield Land! Discover a lucrative investment opportunity in the peaceful city of Sanmu, Chiba Prefecture. This property features a prefabricated office building currently leased to a corporate tenant, ensuring stable monthly rental income. Situated on a 164㎡ land parcel with an additional 32㎡ shared private road, this site offers high yield returns of approximately 18%, making it an ideal choice for investors seeking a low-cost, high-return asset. The location is conveniently accessible, just a 10-minute drive from JR Yachimata Station on the Sobu Line. The property benefits from freehold ownership, immediate transfer availability, and a secured lease with a guarantee company. Don't miss this affordable and promising investment in a growing region.",
    features: [
      'Prefabricated Office Building',
      'Rental Income: ¥25,000/month (¥300,000 annually)',
      'Yield: Approx. 18% (Owner change / Tenanted)',
      'Nearest Station: JR Sobu Line – Yachimata Station (Approx. 10 min by car)',
      'Structure / Use: Prefabricated office (currently leased to corporate tenant)',
      'Land Area: 164㎡ (approx. 49.6 tsubo) + Private road shared area 32㎡',
      'Ownership: Freehold',
      'Land Category: Forest land',
      'Urban Planning: Non-designated urban planning area (Non-zoned)',
      'Zoning: Unspecified use zone',
      'Building Coverage / Floor Area Ratio: 60% / 200%',
      'Road Access: Frontage on 4m wide road (north side)',
      'Delivery: Immediate',
      'Rental Status: Leased to corporation with guarantee company contract',
      'Remarks: High yield, low price – prefab office included, guarantee company contract in place',
      'Layout: Prefabricated office',
      'Building Area: Please contact us for more information',
      'Land Area: 164㎡',
      'Bedrooms/Toilets: Please contact us for more information',
      'Current Rent: ¥25,000/month',
      'Annual Income: ¥300,000/year',
      'Projected Yield: 18%',
      'Tenant Rent: Please contact us for more information',
      'Occupancy Rate: Please contact us for more information',
      'Management: Please contact us for more information',
      'Investment Property',
      'High-Yield Land',
      'Low-Cost Investment',
      'High-Return Asset',
      'Corporate Tenant',
      'Stable Income',
      'Guarantee Company Contract',
      'Affordable Investment',
      'Growing Region',
      'Immediate Transfer',
      'Secured Lease',
    ],
    yearBuilt: 'Please contact us for more information',
    phoneNumber: '+818033666526',
  },
];

export function getPropertyById(id: number): Property | undefined {
  return properties.find(property => property.id === id);
}
