export interface Property {
  id: number;
  title: string;
  price: number;
  annualPrice?: number;
  location: string;
  bedrooms: number | undefined;
  toilets: number | undefined;
  area: number;
  type: 'For Sale' | 'For Rent';
  image: string;
  images: { url: string; title: string }[];
  description: string;
  features: string[];
  yearBuilt: number;
  phoneNumber: string;
}

export const properties: Property[] = [
  {
    id: 1,
    title: 'Yamadadai Owner Change Property',
    price: 4500000,
    location: 'Yamadadai, Yachimata City, Chiba Prefecture',
    bedrooms: 4,
    toilets: 1,
    area: 108.89,
    type: 'For Sale',
    image: '/exterior-1.jpg',
    images: [
      { url: '/exterior-1.jpg', title: 'Exterior View' },
      { url: '/exterior-11.jpg', title: 'Additional Exterior View' },
      { url: '/entrance-1.jpg', title: 'Entrance' },
      { url: '/garden-1.jpg', title: 'Garden View' },
      { url: '/indoor-1.jpg', title: 'Indoor Space' },
      { url: '/kitchen-1.jpg', title: 'Kitchen' },
      { url: '/toilet-1.jpg', title: 'Bathroom' },
      { url: '/washroom-1.jpg', title: 'Washroom' },
      { url: '/indoor-11.jpg', title: 'Additional Indoor Space' },
      { url: '/indoor-111.jpg', title: 'Extra Indoor View' },
      { url: '/garden-11.jpg', title: 'Additional Garden View' },
    ],
    description:
      'This property is a 2-storey, wooden structure with 4 bedrooms, located in Yamadadai, Yachimata City, Chiba Prefecture. The land area is 286.99㎡ and the building area is 108.89㎡. Immediate delivery is available. Owner change property. For rent (all).',
    features: [
      '4 Bedrooms',
      '2-storey',
      'Wooden Structure',
      'Land Area 286.99㎡',
      'Building Area 108.89㎡',
      'Immediate Delivery',
      'Owner Change Property',
      'For Rent (all)',
      'Bike Parking',
      'Field Land Use',
      '60% Building Coverage Ratio',
      '200% Floor Area Ratio',
      'Ownership',
    ],
    yearBuilt: 1971,
    phoneNumber: '+818033666526',
  },
  {
    id: 2,
    title: 'Kawaba 1-building apartment for rent',
    price: 21200000,
    location: 'Kawaba, Togane City, Chiba Prefecture',
    bedrooms: undefined,
    toilets: undefined,
    area: 238.48,
    type: 'For Sale',
    image: '/exterior-2.jpg',
    images: [
      { url: '/exterior-2.jpg', title: 'Exterior' },
      { url: '/exterior-22.jpg', title: 'Exterior' },
      { url: '/parking-2.jpg', title: 'Parking' },
      { url: '/floor-plan-2.jpg', title: 'Floor Plan' },
    ],
    description:
      '2-storey steel frame apartment for sale with 4 rooms, located in Kawaba, Togane City, Chiba Prefecture. Used area: 238.48㎡, land area: 226.23㎡. Parking available. Ownership. Built in November 1988 (35 years old). Immediate consultation for delivery.',
    features: [
      '2-storey',
      'Steel Frame',
      '4 Rooms',
      'Parking Available',
      'Bike Parking',
      'Ownership',
      'Residential Land',
      'Immediate Consultation for Delivery',
      'Current rent: 224,000 yen',
      'Management contract with external guarantee company',
      'Land area 226.23㎡',
      'Used area 238.48㎡',
      'Year Built: 1988',
      '6 units',
    ],
    yearBuilt: 1988,
    phoneNumber: '+818033666526',
  },
  {
    id: 3,
    title: 'Used house in Honsuka, Sanmu city',
    price: 78000000,
    location: 'Honsuka, Sanmu City, Chiba Prefecture',
    bedrooms: 5,
    toilets: undefined,
    area: 205.62,
    type: 'For Sale',
    image: '/exterior-3.jpg',
    images: [
      { url: '/exterior-3.jpg', title: 'Exterior' },
      { url: '/entrance-3.jpg', title: 'Entrance' },
      { url: '/floor-plan-3.jpg', title: 'Floor plan' },
      { url: '/kitchen-3.jpg', title: 'Kitchen' },
      { url: '/toilet-3.jpg', title: 'Toilet' },
      { url: '/washroom-3.jpg', title: 'Washroom' },
      { url: '/indoor-3.jpg', title: 'Indoor' },
      { url: '/indoor-33.jpg', title: 'Indoor 2' },
      { url: '/indoor-333.jpg', title: 'Indoor 3' },
      { url: '/indoor-3333.jpg', title: 'Indoor 4' },
      { url: '/indoor-33333.jpg', title: 'Indoor 5' },
      { url: '/washroom-3.jpg', title: 'Washroom' },
      { url: '/living-3.jpg', title: 'Living' },
      { url: '/toilet-3.jpg', title: 'Toilet' },
      { url: '/parking-garage-3.jpg', title: 'Parking Garage' },
      { url: '/others-3.jpg', title: 'Other' },
      { url: '/other-local-3.jpg', title: 'Other Local' },
    ],
    description:
      'Japanese-style used house in Honsuka, Sanmu City, Chiba Prefecture. 2-storey, wooden structure, 5 bedrooms, building area 205.62㎡, land area 1577.5㎡. Built in June 2010 (14 years old). Parking for 2 or more cars, detached garage, close to the sea (4-minute walk to Motosuka beach). Spacious land, can be used as a vacation home. Immediate delivery available.',
    features: [
      '5 Bedrooms',
      '2-storey',
      'Wooden Structure',
      'Building Area 205.62㎡',
      'Land Area 1577.5㎡',
      'Built in 2010',
      'Parking for 2 or more cars',
      'Detached Garage',
      'Close to Sea (4-min walk to Motosuka beach)',
      'Vacation Home Potential',
      'Immediate Delivery',
      'Magnificent Gate',
      'Natural Materials',
      'Spacious Land',
      'Summer Resort',
      'Ownership',
      'Type 1 Residence Zoning',
      '60% Building Coverage Ratio',
      '200% Floor Area Ratio',
    ],
    yearBuilt: 2010,
    phoneNumber: '+818033666526',
  },
  {
    id: 4,
    title: 'Oamishirasato City Kimimonori Used Detached House',
    price: 17800000,
    location: '2-chome, Kimimonoriminami, Oamishirasato City, Chiba Prefecture',
    bedrooms: 4,
    toilets: 2,
    area: 109.88,
    type: 'For Sale',
    image: '/exterior-4.jpg',
    images: [
      { url: '/exterior-4.jpg', title: 'Exterior' },
      { url: '/exterior-44.jpg', title: 'Exterior 2' },
      { url: '/floor-plan-4.jpg', title: 'Floor plan' },
      { url: '/entrance-4.jpg', title: 'Entrance' },
      { url: '/living-4.jpg', title: 'Living' },
      { url: '/kitchen-4.jpg', title: 'Kitchen' },
      { url: '/washroom-4.jpg', title: 'Washroom' },
      { url: '/washroom-44.jpg', title: 'Washroom 2' },
      { url: '/washroom-444.jpg', title: 'Washroom 3' },
      { url: '/indoor-4.jpg', title: 'Indoor' },
      { url: '/indoor-44.jpg', title: 'Indoor 2' },
      { url: '/indoor-444.jpg', title: 'Indoor 3' },
      { url: '/indoor-4444.jpg', title: 'Indoor 4' },
      { url: '/indoor-44444.jpg', title: 'Indoor 5' },
      { url: '/indoor-444444.jpg', title: 'Indoor 6' },
      { url: '/indoor-4444444.jpg', title: 'Indoor 7' },
      { url: '/garden-4.jpg', title: 'Garden' },
      { url: '/bus-4.jpg', title: 'Bus' },
      { url: '/toilet-4.jpg', title: 'Toilet' },
      { url: '/toilet-44.jpg', title: 'Toilet 2' },
    ],
    description:
      'Used detached house in Oamishirasato City, Kimimonoriminami, Chiba Prefecture. 2-storey, wooden structure, 4 bedrooms, building area 109.88㎡, land area 139.88㎡. Built in June 1997 (27 years old). Parking available, monitored intercom, reboiling function, city gas, residential land. Exterior (roof and exterior walls) renovated in May 2020. Located in a large development subdivision, close to parks and residential amenities.',
    features: [
      '4 Bedrooms',
      '2-storey',
      'Wooden Structure',
      'Building Area 109.88㎡',
      'Land Area 139.88㎡',
      'Built in 1997',
      'Parking Available',
      'Monitored Intercom',
      'Reboiling Function',
      'System Kitchen',
      'City Gas',
      'Low-rise Residential Area',
      'Residential Land',
      'Renovated in 2020 (roof, exterior walls)',
      'Large Development Subdivision',
      'Close to Parks',
      'Ownership',
      '1st Class Low Class Zoning',
      '50% Building Coverage Ratio',
      '100% Floor Area Ratio',
    ],
    yearBuilt: 1997,
    phoneNumber: '+818033666526',
  },
  {
    id: 5,
    title: 'ComZ Village Tama',
    price: 37500000,
    annualPrice: undefined,
    location: 'Tama, Togane City, Chiba Prefecture',
    bedrooms: undefined,
    toilets: 1,
    area: 90.46,
    type: 'For Sale',
    image: '/exterior-5.jpg',
    images: [
      { url: '/exterior-5.jpg', title: 'Exterior' },
      { url: '/entrance-5.jpg', title: 'Entrance' },
      { url: '/entrance-55.jpg', title: 'Entrance 2' },
      { url: '/living-5.jpg', title: 'Living' },
      { url: '/living-55.jpg', title: 'Living 2' },
      { url: '/kitchen-5.jpg', title: 'Kitchen' },
      { url: '/washroom-5.jpg', title: 'Washroom' },
      { url: '/washroom-55.jpg', title: 'Washroom 2' },
      { url: '/toilet-5.jpg', title: 'Toilet' },
      { url: '/bus-5.jpg', title: 'Bus' },
      { url: '/floor-plan-5.jpg', title: 'Floor plan' },
      { url: '/indoor-5.jpg', title: 'Indoor' },
      { url: '/indoor-55.jpg', title: 'Indoor 2' },
      { url: '/indoor-555.jpg', title: 'Indoor 3' },
      { url: '/storage-5.jpg', title: 'Storage' },
      { url: '/storage-55.jpg', title: 'Storage 2' },
      { url: '/others-local-5.jpg', title: 'Other Local' },
      { url: '/BeisiaToganeStore24minuteswalk1870m-5.jpg', title: 'Beisia Togane Store (24 minutes walk, 1870m)' },
      {
        url: '/ToganeCityHigashiJuniorHighSchool16minuteswalk,1250m-5.jpg',
        title: 'Togane City Higashi Junior High School (16 minutes walk, 1250m)',
      },
    ],
    description:
      'ComZ Village Tama in Tama, Togane City, Chiba Prefecture. 1-storey, wooden structure, 3LDK, building area 90.46㎡, land area 200.7㎡. New construction, built in January 2025. Parking for 2 spaces, monitored intercom, reboiling function, solar power, eco-friendly, BELS/energy-saving standard compliant, public water supply, city gas, and residential land. Courtyard zone, walk-in closet, and more.',
    features: [
      '3LDK',
      '1-storey',
      'Wooden Structure',
      'Building Area 90.46㎡',
      'Land Area 200.7㎡',
      'New Construction (2025)',
      'Parking for 2 Spaces',
      'Monitored Intercom',
      'Reboiling Function',
      'Solar Power',
      'Eco-friendly',
      'Reheating Function',
      'Corner Lot',
      'BELS/Energy-saving Standard Compliant',
      'Public Water Supply',
      'Residential Land',
      'Courtyard Zone',
      'Walk-in Closet',
      'Type 1 Residence Zoning',
      '60% Building Coverage Ratio',
      '200% Floor Area Ratio',
    ],
    yearBuilt: 2025,
    phoneNumber: '+818033666526',
  },
  {
    id: 6,
    title: 'Naruto 2M-1',
    price: 37800000,
    location: 'Naruto, Sanmu City, Chiba Prefecture',
    bedrooms: undefined,
    toilets: 2,
    area: 126.71,
    type: 'For Sale',
    image: '/exterior-6.jpg',
    images: [
      { url: '/exterior-6.jpg', title: 'Exterior' },
      { url: '/exterior-66.jpg', title: 'Exterior 2' },
      { url: '/entrance-6.jpg', title: 'Entrance' },
      { url: '/balcony-6.jpg', title: 'Balcony' },
      { url: '/indoor-6.jpg', title: 'Indoor' },
      { url: '/indoor-66.jpg', title: 'Indoor 2' },
      { url: '/storage-6.jpg', title: 'Storage' },
      { url: '/toilet-6.jpg', title: 'Toilet' },
      { url: '/toilet-second-floor-6.jpg', title: 'Toilet Second Floor' },
      { url: '/washroom-6.jpg', title: 'Washroom' },
      { url: '/bus-6.jpg', title: 'Bus' },
      { url: '/kitchen-stylish-island-6.jpg', title: 'Kitchen Stylish Island' },
      { url: '/living-it-comes-with-storage-for-toys-6.jpg', title: 'Living with Storage for Toys' },
      { url: '/living-kids-space-6.jpg', title: 'Living Kids Space' },
      { url: '/living-6.jpg', title: 'Living' },
      { url: '/floor-plan-6.jpg', title: 'Floor plan' },
    ],
    description:
      'Naruto 2M-1 in Naruto, Sanmu City, Chiba Prefecture. 2-storey, wooden structure, 3LDK, building area 126.71㎡, land area 238.19㎡. For sale. New construction, built in December 2024. Parking for 2 spaces, reboiling function, 2 or more toilets, low-rise residential area, highly airtight and insulated all-electric house, fully equipped, walk-in closet, and more.',
    features: [
      '3LDK',
      '2-storey',
      'Wooden Structure',
      'Building Area 126.71㎡',
      'Land Area 238.19㎡',
      'New Construction (2024)',
      'Parking for 2 Spaces',
      'Monitored Intercom',
      '2 or More Toilets',
      'Low-rise Residential Area',
      'Highly Airtight and Insulated',
      'All-electric House',
      'Fully Equipped',
      'Walk-in Closet',
      'Flat Topography',
      'Ownership',
      '60% Building Coverage Ratio',
      '200% Floor Area Ratio',
    ],
    yearBuilt: 2024,
    phoneNumber: '+818033666526',
  },
  {
    id: 7,
    title: 'Maison Phoenix ABC+ Tenant',
    price: 80000000,
    annualPrice: undefined,
    location: 'Chiba Prefecture, Togane City, Kurume',
    bedrooms: undefined,
    toilets: undefined,
    area: 136.73,
    type: 'For Sale',
    image: '/exterior-2.jpg',
    images: [
      { url: '/exterior-7.jpg', title: 'Exterior' },
      { url: '/exterior-77.jpg', title: 'Exterior 2' },
      { url: '/exterior-777.jpg', title: 'Exterior 3' },
      { url: '/floor-plan-7.jpg', title: 'Floor plan' },
      { url: '/entrance-7.jpg', title: 'Entrance' },
      { url: '/entrance-77.jpg', title: 'Entrance 2' },
      { url: '/common-area-7.jpg', title: 'Common Area' },
      { url: '/balcony-7.jpg', title: 'Balcony' },
      { url: '/indoor-7.jpg', title: 'Indoor' },
      { url: '/indoor-77.jpg', title: 'Indoor 2' },
      { url: '/indoor-777.jpg', title: 'Indoor 3' },
      { url: '/storage-7.jpg', title: 'Storage' },
      { url: '/storage-77.jpg', title: 'Storage 2' },
      { url: '/bus-7.jpg', title: 'Bus' },
      { url: '/others-7.jpg', title: 'Others' },
      { url: '/KumeiStation-7.jpg', title: 'Kumei Station' },
    ],
    description:
      'Maison Phoenix ABC+ Tenant is a 2-storey wooden apartment building for sale in Kurume, Togane City, Chiba Prefecture. Used area: 136.73㎡, land area: 799.73㎡. 17 units (15 apartments + 3 office units). Currently partially rented. Built in February 1992 (33 years old). Bicycle parking available. Residential land. Ownership. Immediate consultation for delivery.',
    features: [
      '2-storey',
      'Wooden Structure',
      '17 Units (15 apartments + 3 office units)',
      'Partially Rented',
      'Bicycle Parking',
      'Residential Land',
      'Ownership',
      'Land Area 799.73㎡',
      'Building Area 136.73㎡',
      'Built in 1992',
      'Immediate Consultation for Delivery',
      'Flat Topography',
      'Non-lined Areas',
      'Studio Units',
    ],
    yearBuilt: 1992,
    phoneNumber: '+818033666526',
  },
  // {
  //   id: 7,
  //   title: 'Waterfront Villa with Private Beach',
  //   price: 3200000,
  //   location: 'Palm Jumeirah, Dubai',
  //   bedrooms: 6,
  //   toilets: 7,
  //   area: 7000,
  //   type: 'For Sale',
  //   image: '/waterfront-villa-exterior.jpg',
  //   images: [
  //     { url: '/waterfront-villa-exterior.jpg', title: 'Exterior View' },
  //     // "/waterfront-villa-living.jpg",
  //     // "/waterfront-villa-kitchen.jpg",
  //     // "/waterfront-villa-bedroom.jpg",
  //     // "/waterfront-villa-beach.jpg",
  //   ],
  //   description:
  //     'Exceptional waterfront villa on Palm Jumeirah with private beach access and unobstructed sea views. This magnificent property offers the ultimate in luxury living with expansive indoor and outdoor spaces designed for comfort and entertainment.\n\nThe grand entrance leads to a double-height living area with floor-to-ceiling windows showcasing the stunning sea views. The villa features a gourmet kitchen, formal dining room, family room, home theater, and a private office.\n\nThe master suite occupies an entire wing of the upper floor and includes a sitting area, walk-in dressing room, and a lavish bathroom with a freestanding tub. Five additional en-suite bedrooms provide ample space for family and guests.\n\nOutdoor amenities include an infinity pool, landscaped garden, private beach, and multiple terraces for dining and relaxation.',
  //   features: [
  //     'Private Beach Access',
  //     'Infinity Pool',
  //     'Home Theater',
  //     'Smart Home System',
  //     'Staff Quarters',
  //     'Elevator',
  //     'Wine Cellar',
  //     'Gym',
  //     'Sauna',
  //     'Multiple Terraces',
  //   ],
  //   yearBuilt: 2021,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 8,
  //   title: 'Modern Studio in Business Bay',
  //   price: 2800,
  //   annualPrice: 33600,
  //   location: 'Business Bay, Dubai',
  //   bedrooms: 0,
  //   toilets: 1,
  //   area: 550,
  //   type: 'For Rent',
  //   image: '/studio-apartment-living.jpg',
  //   images: [
  //     { url: '/studio-apartment-living.jpg', title: 'Living Room' },
  //     // "/studio-apartment-kitchen.jpg",
  //     // "/studio-apartment-bathroom.jpg",
  //     // "/studio-apartment-view.jpg",
  //     // "/studio-apartment-building.jpg",
  //   ],
  //   description:
  //     'Contemporary studio apartment in the vibrant Business Bay district. This well-designed space maximizes functionality without compromising on style and comfort.\n\nThe open-plan layout features a sleeping area, living space, and a fully equipped kitchen with modern appliances. The bathroom includes a walk-in shower and premium fixtures.\n\nFloor-to-ceiling windows offer impressive views of the surrounding cityscape and fill the apartment with natural light. The unit comes fully furnished with high-quality furniture and accessories.\n\nThe building provides excellent amenities including a swimming pool, fitness center, and 24-hour security. Located within walking distance to Dubai Canal and a short drive to Downtown Dubai.',
  //   features: [
  //     'Fully Furnished',
  //     'City Views',
  //     'Built-in Wardrobes',
  //     'Modern Appliances',
  //     'Swimming Pool',
  //     'Gym',
  //     'Covered Parking',
  //     '24/7 Security',
  //     'Central A/C',
  //     'High-speed Internet',
  //   ],
  //   yearBuilt: 2019,
  //   phoneNumber: '+818033666526',
  // },
  // {
  //   id: 9,
  //   title: 'Luxury Golf Course Villa',
  //   price: 1850000,
  //   location: 'Emirates Hills, Dubai',
  //   bedrooms: 5,
  //   toilets: 6,
  //   area: 6000,
  //   type: 'For Sale',
  //   image: '/golf-villa-exterior.jpg',
  //   images: [
  //     { url: '/golf-villa-exterior.jpg', title: 'Exterior View' },
  //     // "/golf-villa-living.jpg",
  //     // "/golf-villa-kitchen.jpg",
  //     // "/golf-villa-bedroom.jpg",
  //     // "/golf-villa-garden.jpg",
  //   ],
  //   description:
  //     "Prestigious villa overlooking the championship golf course in Emirates Hills. This exceptional property combines architectural elegance with modern luxury in one of Dubai's most exclusive communities.\n\nThe grand entrance leads to a spacious living area with high ceilings and panoramic views of the golf course. The ground floor includes a formal dining room, family room, gourmet kitchen with breakfast area, and a guest suite.\n\nThe upper level houses four en-suite bedrooms including the master suite with a private terrace, walk-in closet, and luxurious bathroom. The basement level features a home theater, gym, and staff quarters.\n\nThe outdoor space includes a swimming pool, landscaped garden, and covered terrace with outdoor kitchen and dining area. The property offers privacy and security in a prime location.",
  //   features: [
  //     'Golf Course View',
  //     'Private Swimming Pool',
  //     'Home Theater',
  //     'Gym',
  //     'Staff Quarters',
  //     'Smart Home System',
  //     'Outdoor Kitchen',
  //     'Multiple Terraces',
  //     'Double Garage',
  //     '24/7 Security',
  //   ],
  //   yearBuilt: 2016,
  //   phoneNumber: '+818033666526',
  // },
];

export function getPropertyById(id: number): Property | undefined {
  return properties.find(property => property.id === id);
}
